
export const GET_USERS = 'GET_USERS';
export const USERS_ERROR = 'USERS_ERROR';

export const LOGIN = 'LOGIN';
export const LOGIN_ERROR = 'LOGIN_ERROR';

export const LOAD_CATEGORIES = 'CATEGORIES';
export const LOAD_CATEGORIES_SUCCESS = 'LOAD_CATEGORIES_SUCCESS';
export const LOAD_CATEGORIES_ERROR = 'CATEGORIES_ERROR';

export const LOAD_GENERES_SUCCESS = 'LOAD_GENERES_SUCCESS';
export const LOAD_GENERES_ERROR = 'GENERES_ERROR';

export const LOAD_NEW_RELEASES_SUCCESS = "LOAD_NEW_RELEASES_SUCCESS";

export const LOAD_ALBUMS_SUCCESS = 'LOAD_ALBUMS_SUCCESS';
export const LOAD_ALBUMS_ERROR = 'LOAD_ALBUMS_ERROR';

export const LOAD_NEW_PLAYLIST_SUCCESS = 'LOAD_NEW_PLAYLIST_SUCCESS';
export const LOAD_NEW_PLAYLIST_ERROR = 'LOAD_NEW_PLAYLIST_ERROR';

export const LOAD_SINGLE_CATEGORIES_SUCCESS = 'LOAD_SINGLE_CATEGORIES_SUCCESS';
export const LOAD_SINGLE_CATEGORIES_ERROR = 'LOAD_SINGLE_CATEGORIES_ERROR';