export const PROVA = 'PROVA';
export const GET_USERS = 'GET_USERS';
export const USERS_ERROR = 'USERS_ERROR';
export const LOGIN = 'LOGIN';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const LOAD_CATEGORIES = 'CATEGORIES';
export const LOAD_CATEGORIES_SUCCESS = 'LOAD_CATEGORIES_SUCCESS';
export const LOAD_CATEGORIES_ERROR = 'CATEGORIES_ERROR';