
export const GET_USERS = 'GET_USERS';
export const USERS_ERROR = 'USERS_ERROR';

export const LOGIN = 'LOGIN';
export const LOGIN_ERROR = 'LOGIN_ERROR';

export const LOAD_CATEGORIES = 'LOAD_CATEGORIES';
export const LOAD_CATEGORIES_SUCCESS = 'LOAD_CATEGORIES_SUCCESS';
export const LOAD_CATEGORIES_ERROR = 'CATEGORIES_ERROR';


export const LOAD_GENERES = 'LOAD_GENERES';
export const LOAD_GENERES_SUCCESS = 'LOAD_GENERES_SUCCESS';
export const LOAD_GENERES_ERROR = 'GENERES_ERROR';

export const LOAD_NEW_RELEASES = "LOAD_NEW_RELEASES";
export const LOAD_NEW_RELEASES_SUCCESS = "LOAD_NEW_RELEASES_SUCCESS";
export const LOAD_NEW_RELEASES_ERROR = "LOAD_NEW_RELEASES_SUCCESS";

export const LOAD_ALBUMS = 'LOAD_ALBUMS';
export const LOAD_ALBUMS_SUCCESS = 'LOAD_ALBUMS_SUCCESS';
export const LOAD_ALBUMS_ERROR = 'LOAD_ALBUMS_ERROR';

export const LOAD_NEW_PLAYLIST = 'LOAD_NEW_PLAYLIST';
export const LOAD_NEW_PLAYLIST_SUCCESS = 'LOAD_NEW_PLAYLIST_SUCCESS';
export const LOAD_NEW_PLAYLIST_ERROR = 'LOAD_NEW_PLAYLIST_ERROR';

export const LOAD_SINGLE_CATEGORIES = 'LOAD_SINGLE_CATEGORIES';
export const LOAD_SINGLE_CATEGORIES_SUCCESS = 'LOAD_SINGLE_CATEGORIES_SUCCESS';
export const LOAD_SINGLE_CATEGORIES_ERROR = 'LOAD_SINGLE_CATEGORIES_ERROR';


export const LOAD_USER_PLAYLIST = 'LOAD_USER_PLAYLIST';
export const LOAD_USER_PLAYLIST_SUCCESS = 'LOAD_USER_PLAYLIST_SUCCESS';
export const LOAD_USER_PLAYLIST_ERROR = 'LOAD_USER_PLAYLIST_ERROR';

export const LOAD_SEARCH = 'LOAD_SEARCH_PLAYLIST';
export const LOAD_SEARCH_SUCCESS = 'LOAD_SEARCH_SUCCESS';
export const LOAD_SEARCH_ERROR = 'LOAD_SEARCH_ERROR';

export const SAVE_TRACK = 'SAVE_TRACK';
export const SAVE_TRACK_SUCCESS = 'SAVE_TRACK_SUCCESS';
export const SAVE_TRACK_ERROR = 'SAVE_TRACK_ERROR';

export const GET_USER_PROFILE = 'GET_USER_PROFILE';
export const GET_USER_PROFILE_SUCCESS = 'GET_USER_PROFILE_SUCCESS';
export const GET_USER_PROFILE_ERROR = 'GET_USER_PROFILE_ERROR';

export const DELETE_SONG = 'DELETE_SONG';
export const DELETE_SONG_SUCCESS = 'DELETE_SONG_SUCCESS';
export const DELETE_SONG_ERROR = 'DELETE_SONG_ERROR';

export const GET_SINGLE_PLAYLIST = 'GET_SINGLE_PLAYLIST';
export const GET_SINGLE_PLAYLIST_SUCCESS = 'GET_SINGLE_PLAYLIST_SUCCESS';
export const GET_SINGLE_PLAYLIST_ERROR = 'GET_SINGLE_PLAYLIST_ERROR';

export const GET_SINGLE_TRACK = 'GET_SINGLE_TRACK';
export const GET_SINGLE_TRACK_SUCCESS = 'GET_SINGLE_TRACK_SUCCESS';
export const GET_SINGLE_TRACK_ERROR = 'GET_SINGLE_TRACK_ERROR';

export const DELETE_TRACK_PLAYLIST = 'DELETE_TRACK_PLAYLIST';
export const DELETE_TRACK_PLAYLIST_SUCCESS = 'DELETE_TRACK_PLAYLIST_SUCCESS';
export const DELETE_TRACK_PLAYLIST_ERROR = 'DELETE_TRACK_PLAYLIST_ERROR';

export const ADD_TRACK_PLAYLIST = 'ADD_TRACK_PLAYLIST';
export const ADD_TRACK_PLAYLIST_SUCCESS = 'ADD_TRACK_PLAYLIST_SUCCESS';
export const ADD_TRACK_PLAYLIST_ERROR = 'ADD_TRACK_PLAYLIST_ERROR';
